### ISSUE TITLE
Update for Anniversary Update

### ISSUE THREAD

**Issue by coreypenford** [tommy-josepovic/ror2-editor#1]
New update was released today:
https://store.steampowered.com/news/app/632360/view/3008941395560828301

Your site is the top google result for "risk of rain 2 save editor", so you may get some traffic in the next few weeks. It doesn't seem to currently support the new additions added in this update.

**Comment by tommy-josepovic** [comment]
Thank you for making me recognize the importance of a quick update to the editor. 

The editor should now be up-to-date.
