### ISSUE TITLE
Commented out Blockade Breaker Achievement

### ISSUE THREAD

**Issue by hyperupcall** [tommy-josepovic/ror2-editor#2]
Hello!

First of all, I'd like to say thanks for making this - some modpack I made corrupted my savefile and this app _significantly_ expedited the recovery process :)

Just a quick question, I noticed that the Blockade Breaker achievement was [commented out](https://github.com/tommy-josepovic/ror2-editor/blob/29679f7a8eedc3d41f8bfef77a9d414c9c677011/src/challenges.tsx#L46) - was this intended due to some breakage or maybe it was supposed to be uncommented after some testing?

Thankies,
Edwin

**Comment by tommy-josepovic** [comment]
Blockade Breaker is the only achievement in the game that unlocks two elements.

I didn't test it thoroughly, and left it out in case it broke something.

This might require a bit of refactoring.

**Comment by hyperupcall** [comment]
Ohh, I see - thanks for the explanation
